### ISSUE TITLE
Adding new NFTs on the NFT list

### ISSUE THREAD

**Issue by tempe-techie** [lab10-coop/minerva-nft-list#2]
Hi @seliqui 👋 Thomas told me to contact you about adding new NFTs to the Minerva NFT list.

I've built a domain name system called [Punk Domains](https://punk.domains/) that works on multiple chains (Polygon, Gnosis Chain, Arbitrum, Optimism). Each domain is an ERC-721 NFT and Minerva Wallet quickly finds it and properly shows it right after minting.

Example:

![](https://raw.githubusercontent.com/tempe-techie/images/main/minerva-1.jpg)

The only thing missing is a logo on the NFTs list:

![](https://raw.githubusercontent.com/tempe-techie/images/main/minerva-2.jpg)

@tze42 told me the solution is to add an entry to this file: https://github.com/lab10-coop/minerva-nft-list/blob/main/all.json 

The entry would look like this:

```json
{
    "name": ".gnosis",
    "address": "0xBDACF94dDCAB51c39c2dD50BffEe60Bb8021949a",
    "symbol": ".GNOSIS",
    "chainId": 100,
    "logoURI": "https://raw.githubusercontent.com/tempe-techie/images/main/punk-domains-logo-200.png",
    "override": false
  }
```

Questions:

1. Are there any requirements regarding the logo size? Here I have a 200x200 image - is that too big?
2. Can I make a pull request to enter NFT data to this list? Or do you rather do it yourself? (Both is fine with me)

**Comment by PeterTheOne** [comment]
@tempe-techie Hi, entry looks good! About the logo: We prefer a simple and small SVG image, the link could point to your own site or you can add the logo to this repo here. Feel free to create PR yourself for all your NFT contracts!

**Comment by tempe-techie** [comment]
Thanks, I created the PR now 🙂 https://github.com/lab10-coop/minerva-nft-list/pull/3
