### ISSUE TITLE
Add NFT collection: AzuroBet-NFT

### ISSUE THREAD

**Issue by PeterTheOne** [lab10-coop/minerva-nft-list#6]
I would to have the following NFT collection added:

- Name: AzuroBet-NFT
- Symbol: BET
- Address: [0xFd9E5A2A1bfc8B57A288A3e12E2c601b0Cc7e476](https://blockscout.com/xdai/mainnet/token/0xFd9E5A2A1bfc8B57A288A3e12E2c601b0Cc7e476/token-transfers)
- ChainId: 100
- LogoURI: todo: https://azuro.org/ and https://bookmaker.xyz/
- Override: false

@seliqui Do you want to help with a logo?

**Comment by seliqui** [comment]
Done via this commit:
https://github.com/lab10-coop/minerva-nft-list/commit/322238c5733483ae85cb949b092654bcf686573a
